In [1]:
import pandas as pd

In [2]:
# to check version
print(pd.__version__)

1.0.1


In [30]:
# Series
arr =[0,1,2,3,4]
s1=pd.Series(arr)
print(s1)

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [8]:
order=[1,2,3,4]
s2=pd.Series(arr, index=order)
print(s2)

1    1
2    2
3    3
4    4
dtype: int64


In [9]:
import numpy as np
n=np.random.randn(5)
index=['a','b','c','d','e']
s2=pd.Series(n ,index = index)
print(s2)

a    1.162385
b    0.256391
c    1.272094
d    0.191469
e   -1.394045
dtype: float64


In [11]:
d={'a':1,'b':2,'c':3,'d':4,'e':5}
s3=pd.Series(d)
print(s3)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [4]:
s1=pd.DataFrame(['A','B','C','D'])
print(s1)

   0
0  A
1  B
2  C
3  D


In [6]:
# slicing
a=s1[0:3]
a

0
0  A
1  B
2  C

In [17]:
s4=s1.append(s3)
print(s4)

A    1
B    2
C    3
D    4
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [19]:
# to del or drop
s4.drop('a')

A    1
B    2
C    3
D    4
b    2
c    3
d    4
e    5
dtype: int64

In [22]:
arr2=[1,2,3,4,5,6,7]
arr3=[6,7,8,9,5]

In [23]:
s5=pd.Series(arr2)
s6=pd.Series(arr3)

In [ ]:
# ops

In [25]:
s5.add(s6)

0     7.0
1     9.0
2    11.0
3    13.0
4    10.0
5     NaN
6     NaN
dtype: float64

In [26]:
s5.sub(s6)

0   -5.0
1   -5.0
2   -5.0
3   -5.0
4    0.0
5    NaN
6    NaN
dtype: float64

In [27]:
s5.mul(s6)

0     6.0
1    14.0
2    24.0
3    36.0
4    25.0
5     NaN
6     NaN
dtype: float64

In [28]:
s5.div(s6)

0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    1.000000
5         NaN
6         NaN
dtype: float64

In [33]:
s7=s5.div(s1)

In [34]:
s7.max()

inf

In [ ]:
# data frame

In [2]:
import pandas as pd
df1 = pd.DataFrame()
print(df1)

Empty DataFrame
Columns: []
Index: []


In [36]:
dates = pd.date_range('today',periods=6)
print(dates)

DatetimeIndex(['2020-01-07 14:39:55.681167', '2020-01-08 14:39:55.681167',
               '2020-01-09 14:39:55.681167', '2020-01-10 14:39:55.681167',
               '2020-01-11 14:39:55.681167', '2020-01-12 14:39:55.681167'],
              dtype='datetime64[ns]', freq='D')


In [37]:
num_arr=np.random.randn(6,4)
print(num_arr)

[[ 1.10207419  0.12481785 -0.73087798 -2.32586336]
 [ 0.75482378  0.18507751  0.20246676  1.86180278]
 [ 0.55895946  1.18063477  0.88720961  0.08393736]
 [ 1.76791162  1.71185722 -0.69287115  0.98240542]
 [-1.09470618 -1.1177869   0.39490696 -0.21524848]
 [ 0.04468064  1.18283682  0.00412738 -0.40980049]]


In [38]:
columns=['a','b','c','d']
df1=pd.DataFrame(num_arr, index=dates, columns=columns)
df1

a         b         c         d
2020-01-07 14:39:55.681167  1.102074  0.124818 -0.730878 -2.325863
2020-01-08 14:39:55.681167  0.754824  0.185078  0.202467  1.861803
2020-01-09 14:39:55.681167  0.558959  1.180635  0.887210  0.083937
2020-01-10 14:39:55.681167  1.767912  1.711857 -0.692871  0.982405
2020-01-11 14:39:55.681167 -1.094706 -1.117787  0.394907 -0.215248
2020-01-12 14:39:55.681167  0.044681  1.182837  0.004127 -0.409800

In [39]:
print(df1)

                                   a         b         c         d
2020-01-07 14:39:55.681167  1.102074  0.124818 -0.730878 -2.325863
2020-01-08 14:39:55.681167  0.754824  0.185078  0.202467  1.861803
2020-01-09 14:39:55.681167  0.558959  1.180635  0.887210  0.083937
2020-01-10 14:39:55.681167  1.767912  1.711857 -0.692871  0.982405
2020-01-11 14:39:55.681167 -1.094706 -1.117787  0.394907 -0.215248
2020-01-12 14:39:55.681167  0.044681  1.182837  0.004127 -0.409800


In [52]:
wt=np.random.randint(20,80,100)
ht=np.random.randint(100,200,100)
r_no=np.arange(1,101)
df2=pd.DataFrame({"roll_no":r_no, "Hieght":ht, "Wieght":wt})
df2
#df2=pd.DataFrame(df3, columns=col)

roll_no  Hieght  Wieght
0         1     121      57
1         2     144      73
2         3     147      65
3         4     126      54
4         5     167      40
5         6     100      66
6         7     186      72
7         8     132      20
8         9     136      52
9        10     174      30
10       11     101      29
11       12     181      59
12       13     149      30
13       14     188      39
14       15     122      39
15       16     133      27
16       17     164      42
17       18     149      79
18       19     163      52
19       20     192      59
20       21     123      48
21       22     170      65
22       23     134      69
23       24     183      76
24       25     176      39
25       26     193      54
26       27     146      21
27       28     141      64
28       29     119      66
29       30     111      56
..      ...     ...     ...
70       71     179      20
71       72     184      40
72       73     136      58
73       74     175      52
74       75     182      68
75       76     124      31
76       77     199      32
77       78     195      43
78       79     128      72
79       80     109      68
80       81     145      23
81       82     154      74
82       83     135      55
83       84     156      57
84       85     170      61
85       86     130      32
86       87     128      68
87       88     180      48
88       89     185      69
89       90     129      39
90       91     184      56
91       92     189      25
92       93     151      21
93       94     199      49
94       95     107      52
95       96     154      74
96       97     156      27
97       98     106      48
98       99     116      57
99      100     100      77

[100 rows x 3 columns]

In [48]:
df3=list(zip(r_no,ht,wt)
xyz=pd.DataFrame(df3,columns=col)
xyz

Roll_no  Hieght  weight
0         1     109      49
1         2     100      66
2         3     135      54
3         4     104      67
4         5     136      71
5         6     183      70
6         7     199      37
7         8     164      58
8         9     127      34
9        10     106      79
10       11     138      59
11       12     138      26
12       13     166      61
13       14     168      57
14       15     102      40
15       16     153      23
16       17     105      26
17       18     163      42
18       19     114      63
19       20     163      70
20       21     170      51
21       22     166      22
22       23     165      23
23       24     114      34
24       25     186      78
25       26     183      58
26       27     127      58
27       28     184      70
28       29     182      60
29       30     192      25
..      ...     ...     ...
70       71     106      29
71       72     120      58
72       73     165      30
73       74     184      30
74       75     198      79
75       76     143      22
76       77     178      23
77       78     196      45
78       79     158      50
79       80     184      53
80       81     156      74
81       82     181      40
82       83     168      79
83       84     167      74
84       85     125      40
85       86     101      20
86       87     167      69
87       88     148      69
88       89     198      43
89       90     180      29
90       91     110      73
91       92     156      67
92       93     163      21
93       94     144      20
94       95     144      68
95       96     169      27
96       97     168      56
97       98     185      49
98       99     167      38
99      100     193      62

[100 rows x 3 columns]

In [49]:
data= [['alex',10],['bob',12],['clarke',13]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    alex   10
1     bob   12
2  clarke   13


In [8]:
import pandas as pd
weather_data= {'day':['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
              'temp':[32,35,28,24,32,31,],
                'windspeed':[6,7,2,7,4,2],
                'event':['rain','sunny','snow','snow','rain','sunny']}
df=pd.DataFrame(weather_data)
df

day  temp  windspeed  event
0  1/1/2017    32          6   rain
1  1/2/2017    35          7  sunny
2  1/3/2017    28          2   snow
3  1/4/2017    24          7   snow
4  1/5/2017    32          4   rain
5  1/6/2017    31          2  sunny

In [58]:
# df.shape
rows,columns=df.shape
rows

6

In [59]:
df.columns

Index(['day', 'Temp', 'windspeed', 'event'], dtype='object')

# rows

In [65]:
df.head(2) # default = 5

day  Temp  windspeed  event
0  1/1/2017    32          6   rain
1  1/2/2017    35          7  sunny

In [66]:
df.tail(2)

day  Temp  windspeed  event
4  1/5/2017    32          4   rain
5  1/6/2017    31          2  sunny

In [9]:
df(df[1:3])

TypeError: 'DataFrame' object is not callable

# col

In [71]:
df['Temp']

0    32
1    35
2    28
3    24
4    32
5    31
Name: Temp, dtype: int64

In [72]:
df.Temp

0    32
1    35
2    28
3    24
4    32
5    31
Name: Temp, dtype: int64

In [73]:
df[['temp','day']]

Temp       day
0    32  1/1/2017
1    35  1/2/2017
2    28  1/3/2017
3    24  1/4/2017
4    32  1/5/2017
5    31  1/6/2017

In [74]:
type(df['day'])

pandas.core.series.Series

In [75]:
type(df[['temp','day']])

pandas.core.frame.DataFrame

In [76]:
df['temp'].max()

35

In [77]:
df['Temp']>32

0    False
1     True
2    False
3    False
4    False
5    False
Name: Temp, dtype: bool

In [78]:
df[df['temp']>32]

day  Temp  windspeed  event
1  1/2/2017    35          7  sunny

In [6]:
df[['day','windspeed']][df['windspeed']==df['windspeed'].max()]

day  windspeed
1  1/2/2017          7
3  1/4/2017          7

In [8]:
df['temp'].std()

3.8297084310253524

In [9]:
df['event'].max()

'sunny'

In [10]:
df.describe()

temp  windspeed
count   6.000000   6.000000
mean   30.333333   4.666667
std     3.829708   2.338090
min    24.000000   2.000000
25%    28.750000   2.500000
50%    31.500000   5.000000
75%    32.000000   6.750000
max    35.000000   7.000000

In [ ]:
# set index

In [11]:
df.set_index('day')

temp  windspeed  event
day                             
1/1/2017    32          6   rain
1/2/2017    35          7  sunny
1/3/2017    28          2   snow
1/4/2017    24          7   snow
1/5/2017    32          4   rain
1/6/2017    31          2  sunny

In [12]:
print(df)

        day  temp  windspeed  event
0  1/1/2017    32          6   rain
1  1/2/2017    35          7  sunny
2  1/3/2017    28          2   snow
3  1/4/2017    24          7   snow
4  1/5/2017    32          4   rain
5  1/6/2017    31          2  sunny


In [6]:
df.set_index('day', inplace=True)

In [7]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [8]:
df.loc['1/1/2017'] # works only for index value

temp           32
windspeed       6
event        rain
Name: 1/1/2017, dtype: object

In [9]:
df.reset_index(inplace=True)
df

day  temp  windspeed  event
0  1/1/2017    32          6   rain
1  1/2/2017    35          7  sunny
2  1/3/2017    28          2   snow
3  1/4/2017    24          7   snow
4  1/5/2017    32          4   rain
5  1/6/2017    31          2  sunny

In [10]:
df.loc[1]

day          1/2/2017
temp               35
windspeed           7
event           sunny
Name: 1, dtype: object