In [1]:
import numpy as np
import pandas as pd

In [2]:
# create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having
# random numbers as values?
dates = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
dates

2000-01-01    7
2000-01-08    4
2000-01-15    9
2000-01-22    3
2000-01-29    1
2000-02-05    2
2000-02-12    9
2000-02-19    1
2000-02-26    5
2000-03-04    5
Freq: W-SAT, dtype: int32

In [3]:
# How to filter every nth row in a dataframe?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [4]:
# Write a NumPy program to reverse an array (first element becomes last).
a=np.arange(2,11)
print("The reverse of given array is: ",a[::-1])

The reverse of given array is:  [10  9  8  7  6  5  4  3  2]


In [5]:
# How to split a text column into two separate columns?
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

# Solution
df_out = df.row.str.split(',|\t', expand=True)

# Make first row as header
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka


In [6]:
# Write a NumPy program to add a border (filled with 0's) around an existing array. 

import numpy as np
x = np.zeros((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 1
print(x)


Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
1 on the border and 0 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
# Write a NumPy program to find the set difference of two arrays. 
#The set difference will return the sorted, unique values in array1 that are not in array2. 

import numpy as np
a = np.array([0, 10, 20, 40, 60, 80])
b = [10, 30, 40, 50, 70]
print("The set difference between :",a, "and",b,"is: \n",np.setdiff1d(a,b))


The set difference between : [ 0 10 20 40 60 80] and [10, 30, 40, 50, 70] is: 
 [ 0 20 60 80]


In [8]:
#  Write a NumPy program to compute the multiplication of two given matrixes

a=np.array([0,10,20,30,40,50,60])
b=np.array([1,2,3,4,5,6,7])
c=[]
for i in range(max(len(a),len(b))):
    c.append(a[i]*b[i])
print("The matrix after multiplication is: ",np.array(c))

The matrix after multiplication is:  [  0  20  60 120 200 300 420]


In [9]:
# Write a Pandas program to create a Pivot table and find survival rate by gender on various classes

df = pd.read_csv('titanic.csv')
result = df.pivot_table('survived', index='sex', columns='class')
print(result)

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447


In [10]:
# Write a Pandas program to create a Pivot table and count survival by gender, categories wise age of various classes. 

age = pd.cut(df['age'], [0, 10, 30, 60, 80])
result = df.pivot_table('survived', index=['sex',age], columns='pclass', aggfunc='count')
print(result)

pclass              1     2      3
sex    age                        
female (0, 10]    1.0   8.0   22.0
       (10, 30]  34.0  36.0   57.0
       (30, 60]  48.0  30.0   22.0
       (60, 80]   2.0   NaN    1.0
male   (0, 10]    2.0   9.0   22.0
       (10, 30]  24.0  43.0  151.0
       (30, 60]  63.0  44.0   76.0
       (60, 80]  12.0   3.0    4.0


In [11]:
# Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array

a=[1,2,3,4,5,6,7,8,9,10]
b=np.array(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# Write a Pandas program to create a Pivot table and find number of survivors and average rate grouped by gender and class.

result = df.pivot_table(index='sex', columns='class', aggfunc={'survived':sum, 'fare':'mean'})
print(result)

              fare                       survived             
class        First     Second      Third    First Second Third
sex                                                           
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47


In [13]:
#  Write a Pandas program to create a Pivot table and separate the gender according to whether they traveled alone 
# or not to get the probability of survival.

result = df.pivot_table( 'survived' , [ 'sex' , 'alone' ] , 'class' )
print(result)

class            First    Second     Third
sex    alone                              
female False  0.966667  0.931818  0.416667
       True   0.970588  0.906250  0.616667
male   False  0.425532  0.277778  0.180723
       True   0.333333  0.097222  0.121212


In [14]:
# Write a Pandas program to create a Pivot table and 
# find the probability of survival by class, gender, solo boarding and port of embarkation.

result = df.pivot_table('survived', ['sex' , 'alone' ], [ 'embark_town', 'class' ])
print(result)

embark_town  Cherbourg                     Queenstown                   \
class            First    Second     Third      First Second     Third   
sex    alone                                                             
female False  1.000000  1.000000  0.611111        1.0    NaN  0.625000   
       True   0.944444  1.000000  0.800000        NaN    1.0  0.760000   
male   False  0.473684  0.166667  0.500000        0.0    NaN  0.100000   
       True   0.347826  0.250000  0.151515        NaN    0.0  0.068966   

embark_town  Southampton                      
class              First    Second     Third  
sex    alone                                  
female False    0.941176  0.923077  0.327586  
       True     1.000000  0.892857  0.466667  
male   False    0.407407  0.300000  0.142857  
       True     0.326923  0.089552  0.123762  


In [15]:
# Write a Pandas program to create a Pivot table and check missing values of children.

result = df.loc[df['who']=='child'].isnull().sum()
print(result)

survived        0
pclass          0
sex             0
age             0
sibsp           0
parch           0
fare            0
embarked        0
class           0
who             0
adult_male      0
deck           70
embark_town     0
alive           0
alone           0
Unnamed: 15    83
dtype: int64
