In [1]:
l1=[1,2,3,4]
l1/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [1]:
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [6]:
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [23]:
b=np.array([[1,2.0,"abc",("a","b",1,2),True],[1,2,3,4]])
print(b)
print(type(b))

[list([1, 2.0, 'abc', ('a', 'b', 1, 2), True]) list([1, 2, 3, 4])]
<class 'numpy.ndarray'>


In [16]:
a.ndim

1

In [17]:
a.shape # outermost mein kitne hai unka count

(4,)

In [19]:
len(a)

4

In [22]:
b.shape

(2, 5)

In [24]:
len(b)

2

In [25]:
b.ndim

1

In [27]:
c=np.array([[7,8,9],[4,5,6],[1,2,3]])
c
print(c.shape)
print(c.ndim)
print(len(c))

(3, 3)
2
3


In [28]:
d=np.array([7,8,9],[4,5,6],[1,2,3],[1,2,3,4,5], ndmin=3) # takes only one list
d

ValueError: only 2 non-keyword arguments accepted

In [ ]:
a1=np.array

In [34]:
a1=np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))
print(id(a))
b=a
print(id(b))

[1 2 3 4]
<class 'numpy.ndarray'>
1966755645600
1966755645600


In [17]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
c=np.array([[[1,2],[3,4]],[[1,1],[2,2]]])
print(c[1][1][0])


[[1 2 3]
 [4 5 6]]
2


In [18]:
z1=np.mat([[1,2,3],[4,5,6]])
print(z1)

[[1 2 3]
 [4 5 6]]


In [19]:
# arange method
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [24]:
print(np.arange(1,10))
print(np.arange(3.0))
print(np.arange(0,10,2))
print(np.arange(10,dtype="complex"))
print(np.arange(1,10,2,dtype="float"))

[1 2 3 4 5 6 7 8 9]
[0. 1. 2.]
[0 2 4 6 8]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]
[1. 3. 5. 7. 9.]


In [25]:
# ones method
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [38]:
print(np.ones(5))
print()
print()
print(np.ones((2,3)))
print()
print()
s=(5,6)
print(np.ones(s,dtype=int)) # default dtype is float
print()
print()
print(np.ones((3,4,5)))

[1. 1. 1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]]


[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [39]:
# empty method
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [45]:
print(np.empty(6,dtype=int))
print()
print()
print(np.empty([3,2],dtype=int))

[         0          0          0 1072693248          0 1073741824]


[[         0          0]
 [         0 1072693248]
 [         0 1073741824]]


In [46]:
# zeroes method
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [47]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [48]:
# linspace
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [58]:
print(np.linspace(1,2,retstep=True)) # retstep is dif btw any 2 adj values 0.02040816326530612
print()
print(np.linspace(0,100,5))
print()
print(np.linspace(1,100,endpoint=False,retstep=True))

(array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ]), 0.02040816326530612)

[  0.  25.  50.  75. 100.]

(array([ 1.  ,  2.98,  4.96,  6.94,  8.92, 10.9 , 12.88, 14.86, 16.84,
       18.82, 20.8 , 22.78, 24.76, 26.74, 28.72, 30.7 , 32.68, 34.66,
       36.64, 38.62, 40.6 , 42.58, 44.56, 46.54, 48.52, 50.5 , 52.48,
       54.46, 56.44, 58.42, 60.4 , 62.38, 64.36, 66.34, 68.32, 70.

In [59]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [60]:
print(np.eye(5))
print()
print(np.eye(2,3))
print()
print(np.eye(3,3))
print()
print(np.eye(4,k=-2)) # lower triangula shift diagonal position
print()
print(np.eye(4,k=2)) # upper triangula shift diagonal position


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [61]:
# identity method
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[ 1.,  0.,  0.],
           [ 0.,  1.,  0.],
           [ 0.,  0.,  1.]])



In [62]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
# diag method
print(np.diag(np.array([1,2,3,4]))) # prints diagonal matrix

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# random number gen

In [66]:
np.random.rand(4)

array([0.60062731, 0.57172654, 0.85631759, 0.39306165])

In [67]:
np.random.rand(4,5)

array([[0.95872464, 0.91542129, 0.66852075, 0.50680264, 0.65047404],
       [0.96887428, 0.75133159, 0.51890536, 0.10610436, 0.06672064],
       [0.7325292 , 0.12411856, 0.86902059, 0.45579027, 0.01825915],
       [0.0217298 , 0.72724942, 0.46521006, 0.56825113, 0.28835169]])

In [68]:
np.random.rand(2,3,4)

array([[[0.37087853, 0.13031181, 0.84261628, 0.33464452],
        [0.23440622, 0.66296906, 0.32915167, 0.57698716],
        [0.19238865, 0.10345366, 0.18198635, 0.38667772]],

       [[0.6056713 , 0.02463956, 0.20599343, 0.84478767],
        [0.18111511, 0.11753711, 0.92007198, 0.32890061],
        [0.06032784, 0.71473639, 0.8747131 , 0.26577081]]])

In [69]:
np.random.randint(0,6,9) # start stop and no. of values

array([5, 0, 4, 4, 4, 3, 1, 3, 4])

In [71]:
np.random.randint(2,8,size=(3,3))

array([[2, 4, 2],
       [3, 5, 7],
       [2, 6, 6]])

In [74]:
np.random.randint(2,8,size=(2,4,7))

array([[[6, 4, 5, 4, 6, 4, 4],
        [4, 3, 5, 5, 2, 3, 7],
        [7, 7, 5, 7, 5, 6, 7],
        [7, 3, 5, 3, 7, 2, 5]],

       [[6, 6, 7, 6, 6, 6, 4],
        [5, 4, 4, 3, 6, 7, 2],
        [7, 7, 5, 7, 4, 5, 6],
        [6, 3, 2, 6, 2, 2, 7]]])

In [75]:
np.random.randn(6)

array([ 1.71953306,  0.81663696, -1.71261406, -1.13530408,  0.87046431,
        0.24418102])

In [76]:
np.random.randn(6,7)

array([[-0.00699698, -1.38465689, -0.03252516, -2.41016769,  0.11726223,
         1.55796088,  0.26985178],
       [ 2.75427556,  0.02780171, -1.85992973, -0.71247605, -0.67205032,
        -0.15447222, -0.07625104],
       [-1.35968019,  0.08681864,  0.05197838,  3.12028269,  1.86683441,
        -0.10177042,  0.58146806],
       [-0.27098958,  0.02794275,  0.93555565,  0.46975408,  0.36797594,
         0.8666831 , -0.41894577],
       [ 1.80795526,  0.37661346, -0.61434686, -0.5012777 , -0.69490403,
        -0.20791906,  0.84770491],
       [-0.61101699, -0.51209449, -0.77841577,  1.2395626 ,  0.55126213,
        -1.87250148, -0.10074836]])

In [82]:
np.random.randn(2,4,4)*2+3 # ops performed

array([[[ 4.57200998,  3.45537654,  5.15861513,  2.06026608],
        [ 1.74232806,  2.71570174,  2.79873356,  0.64470284],
        [ 1.85800173,  4.01400857,  6.75843469,  3.32843793],
        [ 3.11315109,  3.79496771,  2.42337165,  2.04793418]],

       [[ 1.44613151,  3.15734019,  3.74558555,  3.88058753],
        [ 1.61534793,  3.40285196,  3.80562326,  6.03613996],
        [ 1.39980711,  1.8505111 ,  4.92551671,  0.82462186],
        [ 5.39849266, -0.11744583,  1.63963223,  4.69765163]]])

In [83]:
a=np.array([1,2,3],float)
b=a
c=a.copy()
a[0]=0
print(a)
print(b)
print(c)
print(id(a))
print(id(b))
print(id(c))

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]
1966773634672
1966773634672
1966756361040


In [85]:
a=np.array([1,2,3],float)
print(a)
print(a.tolist())
st=a.tostring() # encryption/stenography
print(st)
print(np.fromstring(st))

[1. 2. 3.]
[1.0, 2.0, 3.0]
b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'
[1. 2. 3.]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


In [88]:
# for int input
a=np.array([1,2,3])
print(a)
print(a.tolist())
st=a.tostring()
print(st)
print(np.fromstring(st,dtype=int))

[1 2 3]
[1, 2, 3]
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'
[1 2 3]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  import sys


In [93]:
b=np.array([1,2,3],float)
print(b)
b.fill(0)
print(b)

[1. 2. 3.]
[0. 0. 0.]


In [94]:
a=np.array(range(6),float).reshape((2,3))
print(a)
a.transpose()

[[0. 1. 2.]
 [3. 4. 5.]]


array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [ ]:
b=np.array([[1,2,3],[4,5,6]], float)


In [ ]:
# axis = 0 column wise
# axis = 1 row wise
# if f(x) = x^2-3x
# max=x
# argmax=(max(f(x)))
# fancy indexing ind=[3,5,6]
# print(a[ind])
# sparse matrix - non zero value returned with position rxc

In [95]:
matrix=np.mat([[1,2,3],[3,3,2],[4,5,6]])
add_100=lambda i:i+100
vectorized_mat=np.vectorize(add_100) # create a vectorised
vectorized_mat(matrix) # apply vectorisation effect on 

matrix([[101, 102, 103],
        [103, 103, 102],
        [104, 105, 106]])

In [96]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a, b, c))
array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

NameError: name 'array' is not defined

In [5]:
import numpy as np
from scipy import sparse
matrix=np.mat([[0,0],[1,1],[3,0]])
sparse_matrix=sparse.csr_matrix(matrix)
print(matrix)
print(sparse_matrix)

[[0 0]
 [1 1]
 [3 0]]
  (1, 0)	1
  (1, 1)	1
  (2, 0)	3


In [6]:
x= np.mat([0,0,0],[0,0,0],[0,0,0])
x

TypeError: asmatrix() takes from 1 to 2 positional arguments but 3 were given

In [4]:
import numpy as np
import time
import sys

# let's declare the size
Size = 100000

# Creating two lists
list1 = range(Size)
list2 = range(Size)

# Creating two NumPy arrays
arr1 = np.arange(Size)
arr2 = np.arange(Size)

# Calculating time for Python list
start = time.time()
result = [(x,y) for x, y in zip(list1, list2)]
          
print("Time for Python List in msec: ", (time.time() - start) * 1000)

# Calculating time for NumPy array
start = time.time()
result = arr1  , arr2
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)

Time for Python List in msec:  127.96139717102051
Time for NumPy array in msec:  11.997461318969727
